### ISSUE TITLE
sys-ftpd made a kip

### ISSUE THREAD

**Issue by ITotalJustice** [PurpleMyst/scylla#1]
So i noticed that sys ftpd is being made as a kip. Can you try changing it to just make all (or just make), it should then make it a nsp. Rename that to exefs.nsp and add that into a folder called

420000000000000E

That then should be added to ams/titles/ or reinx/titles or sxos/titles.

Haven't tested myself, but that should just work tm.

**Comment by PurpleMyst** [comment]
Thank you for the suggestion.
If I may ask, why is `420000000000000E` the folder name?

**Comment by ITotalJustice** [comment]
It’s just the folder name they decided to go with, it can be changed to almost anything by changing the define in the source code, including the .json file.

As for why they chose the actual name, maybe because it’s 420 (420E sounds the same) haha.

**Comment by PurpleMyst** [comment]
Does this apply to every `.kip`?

**Comment by ITotalJustice** [comment]
Does what apply? It being made into an nsp? Or the title ID?

**Comment by PurpleMyst** [comment]
It being able to be installed into `/atmosphere/titles`

**Comment by ITotalJustice** [comment]
No, kips go into ams/kip (or ams/kips can’t remember) for loading with ams, or add then to the hekate config for hekate.

nsp sys modules go into titles. In general, doesn’t everything use nsp format now? Only sys mod I can think of is nxsh

**Comment by PurpleMyst** [comment]
Alright then, thank you very much for your help. I have fixed it and it should work now :) :octocat:

**Comment by ITotalJustice** [comment]
Perfect, nice one mate!
